### ISSUE TITLE
Problem with project build

### ISSUE THREAD

**Issue by RobertBendun** [zhiayang/sap#6]
I'm having issue with building this project.
Running `python make.py` from project root yielded me this error:

```
build/3.cpp:2057:10: fatal error: './builtin_afms/times_roman.h' file not found
#include "./builtin_afms/times_roman.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Exception in thread Thread-4 (job):
external/miniz/miniz.c
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diana/repos/sap/make.py", line 395, in job
    execvp(
  File "/home/diana/repos/sap/make.py", line 42, in execvp
    return subprocess.check_output(cmd).decode()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['clang++', '-include', 'build/source/include/precompile.h', '-g', '-O0', '-fsanitize=address', '-Wno-old-style-cast', '-std=c++20', '-fno-exceptions', '-I/usr/include/freetype2', '-I/usr/include/libpng16', '-I/usr/include/harfbuzz', '-I/usr/include/glib-2.0', '-I/usr/lib/glib-2.0/include', '-I/usr/include/sysprof-4', '-pthread', '-Wno-padded', '-Wno-cast-align', '-Wno-unreachable-code', '-Wno-packed', '-Wno-missing-noreturn', '-Wno-float-equal', '-Wno-unused-macros', '-Wextra', '-Wconversion', '-Wpedantic', '-Wall', '-Wno-unused-parameter', '-Wno-trigraphs', '-Werror', '-Wno-error=unused-parameter', '-Wno-error=unused-variable', '-Wno-error=unused-function', '-Wno-unused-but-set-variable', '-Werror', '-Wno-error=unused-parameter', '-Wno-error=unused-variable', '-Wno-error=unused-function', '-Wno-unused-but-set-variable', '-DUSE_FONTCONFIG=1', '-Isource/include', '-Iexternal', '-c', '-o', 'build/3.o', 'build/3.cpp']' returned non-zero exit status 1.
```

which doesn't produce `build/3.o` which fails to build a project. I'm using clang 15 on linux if this could help.

**Comment by zhiayang** [comment]
Can you try using the makefile instead? we haven't really tested the python build script too much.

**Comment by RobertBendun** [comment]
Works, thanks!
